/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id            INT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL, 
    date_of_birth DATE NOT NULL, 
    escape_attempts INT NOT NULL, 
    neutered BOOLEAN NOT NULL, 
    weight_kg DECIMAL NOT NULL,
    PRIMARY KEY(id)
);

 ALter table animals ADD species TEXT NOT NULL;

 